language: php

php:
    - 7.2
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: SYMFONY_VERSION='dev-master'
    allow_failures:
        - php: 7.2
          env: SYMFONY_VERSION='dev-master'

before_install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/messenger=$SYMFONY_VERSION; fi

install: composer update $COMPOSER_FLAGS --prefer-dist --no-progress

script: vendor/bin/phpunit
